### ISSUE TITLE
Support for "All Day" events

### ISSUE THREAD

**Issue by agersoncgps** [vonovak/react-native-add-calendar-event#12]
Does this module support passing events into to the eventConfig with only dates and no times, or with the "All-day" option pre checked?

**Comment by vonovak** [comment]
hello, no, the module doesn't support this. However, adding support for this ought to be trivial, and a PR would be merged. If you want to implement this, look [here](https://github.com/vonovak/react-native-add-calendar-event/blob/48a36bb1101ba26a08df0736ffe03692f7b85c13/ios/AddCalendarEvent.m#L91) for ios, and [here](https://github.com/vonovak/react-native-add-calendar-event/blob/48a36bb1101ba26a08df0736ffe03692f7b85c13/android/src/main/java/com/vonovak/AddCalendarEventModule.java#L49) for android.

**Comment by agersoncgps** [comment]
Ok, thanks, I will give it a try. Would the same be true about no end time? Is it not currently supported in the module or does the iOS and Android calendar API require it when creating a new event?

**Comment by vonovak** [comment]
Hi! Ok, looking forward. As for the end time, i believe it is required, but
your best bet is just to try it out.

On Oct 15, 2017 8:48 PM, "Adam Gerson" <notifications@github.com> wrote:

Ok, thanks, I will give it a try. Would the same be true about no end time?
Is it not currently supported in the module or does the iOS and Android
calendar API require it when creating a new event?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/vonovak/react-native-add-calendar-event/issues/12#issuecomment-336732432>,
or mute the thread

**Comment by vonovak** [comment]
this is released in 1.1.0
