### ISSUE TITLE
Question: will this ask to choose a calendar app if a user has multiple calendar apps?

### ISSUE THREAD

**Issue by Minishlink** [vonovak/react-native-add-calendar-event#23]
Hello,

Some users would like to be able to choose their calendar app when adding an event. Currently, we use https://github.com/wmcmahan/react-native-calendar-events/, but this module adds events to the default calendar. I see that the Android implementation of this module is different (you're using `Intent` instead of `ContentResolver`), so I'm guessing this could be the case. Could you confirm? 😃 

Thanks for your open-source work !

**Comment by vonovak** [comment]
Hi Louis,
I haven't tried using this module with multiple calendar apps installed and
am vacationing atm so I can't say for sure, but I think it should do the
job.




On Mar 3, 2018 10:55 PM, "Louis Lagrange" <notifications@github.com> wrote:

Hello,

Some users would like to be able to choose their calendar app when adding
an event. Currently, we use https://github.com/wmcmahan/
react-native-calendar-events/, but this module adds events to the default
calendar. I see that the Android implementation of this module is different
(you're using Intents instead of ContentResolver), so I'm guessing this
could be the case. Could you confirm? 😃

Thanks for your open-source work !

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/vonovak/react-native-add-calendar-event/issues/23>, or mute
the thread

**Comment by Minishlink** [comment]
Thanks! Will keep you updated once tested :)

**Comment by Minishlink** [comment]
Works great on Android :)
You seem to be able to choose the calendar on iOS too.

**Comment by vonovak** [comment]
thanks for getting back @Minishlink

**Comment by rodrigolabs** [comment]
I'm testing on iOS and it's not asking to choose a calendar, only on Android.
I even tried to remove the default Calendar app, and when I try to add an event I get a success message but the event wasn't added anywhere.

@Minishlink have you testes on iOS? Did you get the same behavior?
